# @package _group_

conf_name: object_0_shape_train
run_name: ${conf_name}_${now:%d-%m-%Y_%H-%M-%S}

# paths ###################
# location of the checkpoint to resume training from
ckpt: null
# location of the output directory (where checkpoints and log images will be saved)
out_root_dir: /home/max/thesis/COIGAN-controllable-object-inpainting/experiments_shape
# location of checkpoint dir
ckpt_dir: ${out_root_dir}/${run_name}/checkpoints
# location samples folder
sampl_dir: ${out_root_dir}/${run_name}/samples
###########################

# dataset parameters
data_root_dir: /home/max/thesis/COIGAN-controllable-object-inpainting/datasets/severstal_steel_defect_dataset/test_1/object_datasets/object_dataset_0
binary: True
sample_shapes: [1, 3]
strategy: random
num_workers: 4

# model parameters
size: 256 # size of the output image
channels: 3 # number of channels in the output image #NOTE: swagan has some bug with only 1 channel, but work smoothly with 3 channels!
channel_multiplier: 2 # scale the number of weights
latent: 512 # size of the latent vector
n_mlp: 8 # number of layers in the mapping network

# training parameters
start_iter: 0
iter: 800000
batch: 32
n_sample: 64
mixing: 0.9
lr: 0.002
augment: True
augmentation_preset: preset_1 # present in shape_training/data/augmentation_presets

# regularization parameters
r1: 10
path_regularize: 2
path_batch_shrink: 2
d_reg_every: 16
g_reg_every: 4

# training options
distributed: False

# datalogging options (wandb)
wandb: True # set to false if you don't want to use wandb
wandb_project: shape_stylegan2_object_0
wandb_entity: max_svm
wandb_mode: online

defaults:
  - hydra: overrides

version_base: 1.1